[project]
name = "stack-exchange-classifier"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyter>=1.1.1",
    "pandas>=2.2.3",
    "scikit-learn>=1.6.0",
    "spacy-sentence-bert>=0.1.2",
    "tqdm>=4.67.1",
]
